spring.application.name=library-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/library-backend
spring.datasource.username=postgres
spring.datasource.password=j4n1ele@3011

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
